import * as api from '../api/roles';
import { makeApiActionCreator } from './utils';

export const ROLE_FETCH_DATA_START = 'ROLE/ROLE_FETCH_DATA_START';
export const ROLE_FETCH_DATA_SUCCESS = 'ROLE/ROLE_FETCH_DATA_SUCCESS';
export const ROLE_FETCH_DATA_ERROR = 'ROLE/ROLE_FETCH_DATA_ERROR';

export const ROLE_ADD_DATA_START = 'ROLE/ROLE_ADD_DATA_START';
export const ROLE_ADD_SUCCESS = 'ROLE/ROLE_ADD_SUCCESS';
export const ROLE_ADD_DATA_ERROR = 'ROLE/ROLE_ADD_DATA_ERROR';

export const ROLE_EDIT_DATA_START = 'ROLE/ROLE_EDIT_DATA_START';
export const ROLE_EDIT_SUCCESS = 'ROLE/ROLE_EDIT_SUCCESS';
export const ROLE_EDIT_DATA_ERROR = 'ROLE/ROLE_EDIT_DATA_ERROR';

export const ROLE_REMOVE_START = 'ROLE/ROLE_REMOVE_START';
export const ROLE_REMOVE_SUCCESS = 'ROLE/ROLE_REMOVE_SUCCESS';
export const ROLE_REMOVE_ERROR = 'ROLE/ROLE_REMOVE_ERROR';

export const RIGHTS_FETCH_DATA_START = 'RIGHTS/RIGHTS_FETCH_DATA_START';
export const RIGHTS_FETCH_DATA_SUCCESS = 'RIGHTS/RIGHTS_FETCH_DATA_SUCCESS';
export const RIGHTS_FETCH_DATA_ERROR = 'RIGHTS/RIGHTS_FETCH_DATA_ERROR';

export const RIGHTS_OPTIONS_FETCH_DATA_START = 'RIGHTS/RIGHTS_OPTIONS_FETCH_DATA_START';
export const RIGHTS_OPTIONS_FETCH_DATA_SUCCESS = 'RIGHTS/RIGHTS_OPTIONS_FETCH_DATA_SUCCESS';
export const RIGHTS_OPTIONS_FETCH_DATA_ERROR = 'RIGHTS/RIGHTS_OPTIONS_FETCH_DATA_ERROR';

export const RIGHTS_ADD_START = 'RIGHTS/RIGHTS_ADD_START';
export const RIGHTS_ADD_SUCCESS = 'RIGHTS/RIGHTS_ADD_SUCCESS';
export const RIGHTS_ADD_ERROR = 'RIGHTS/RIGHTS_ADD_ERROR';

export const RIGHTS_REMOVE_START = 'RIGHTS/RIGHTS_REMOVE_START';
export const RIGHTS_REMOVE_SUCCESS = 'RIGHTS/RIGHTS_REMOVE_SUCCESS';
export const RIGHTS_REMOVE_ERROR = 'RIGHTS/RIGHTS_REMOVE_ERROR';

export const fetchRoleData = makeApiActionCreator(api.fetchRoleData, ROLE_FETCH_DATA_START, ROLE_FETCH_DATA_SUCCESS, ROLE_FETCH_DATA_ERROR);
export const addRole = makeApiActionCreator(api.addRole, ROLE_ADD_DATA_START, ROLE_ADD_SUCCESS, ROLE_ADD_DATA_ERROR);
export const editRole = makeApiActionCreator(api.editRole, ROLE_EDIT_DATA_START, ROLE_EDIT_SUCCESS, ROLE_EDIT_DATA_ERROR);
export const deleteRole = makeApiActionCreator(api.deleteRole, ROLE_REMOVE_START, ROLE_REMOVE_SUCCESS, ROLE_REMOVE_ERROR);
export const fetchRightsOptionsData = makeApiActionCreator(api.fetchRightsOptionsData, RIGHTS_OPTIONS_FETCH_DATA_START, RIGHTS_OPTIONS_FETCH_DATA_SUCCESS, RIGHTS_OPTIONS_FETCH_DATA_ERROR);
export const fetchRightsData = makeApiActionCreator(api.fetchRightsData, RIGHTS_FETCH_DATA_START, RIGHTS_FETCH_DATA_SUCCESS, RIGHTS_FETCH_DATA_ERROR);
export const addRights = makeApiActionCreator(api.addRights, RIGHTS_ADD_START, RIGHTS_ADD_SUCCESS, RIGHTS_ADD_ERROR);
export const deleteRights = makeApiActionCreator(api.deleteRights, RIGHTS_REMOVE_START, RIGHTS_REMOVE_SUCCESS, RIGHTS_REMOVE_ERROR);
