import * as api from '../api/users';
import { makeApiActionCreator } from './utils';

export const USERS_FETCH_DATA_START = 'USERS/USERS_FETCH_DATA_START';
export const USERS_FETCH_DATA_SUCCESS = 'USERS/USERS_FETCH_DATA_SUCCESS';
export const USERS_FETCH_DATA_ERROR = 'USERS/USERS_FETCH_DATA_ERROR';

export const USER_REMOVE_START = 'USER/USER_REMOVE_START';
export const USER_REMOVE_SUCCESS = 'USER/USER_REMOVE_SUCCESS';
export const USER_REMOVE_ERROR = 'USER/USER_REMOVE_ERROR';

export const USER_ADD_START = 'USER/USER_ADD_START';
export const USER_ADD_SUCCESS = 'USER/USER_ADD_SUCCESS';
export const USER_ADD_ERROR = 'USER/USER_ADD_ERROR';

export const USER_EDIT_START = 'USER/USER_EDIT_START';
export const USER_EDIT_SUCCESS = 'USER/USER_EDIT_SUCCESS';
export const USER_EDIT_ERROR = 'USER/USER_EDIT_ERROR';

export const USER_EDIT_NAME_START = 'USER/USER_EDIT_NAME_START';
export const USER_EDIT_NAME_SUCCESS = 'USER/USER_EDIT_NAME_SUCCESS';
export const USER_EDIT_NAME_ERROR = 'USER/USER_EDIT_NAME_ERROR';

export const USER_ADD_MODULE_START = 'USER/USER_ADD_MODULE_START';
export const USER_ADD_MODULE_SUCCESS = 'USER/USER_ADD_MODULE_SUCCESS';
export const USER_ADD_MODULE_ERROR = 'USER/USER_ADD_MODULE_ERROR';

export const USER_ADD_ROLE_START = 'USER/USER_ADD_ROLE_START';
export const USER_ADD_ROLE_SUCCESS = 'USER/USER_ADD_ROLE_SUCCESS';
export const USER_ADD_ROLE_ERROR = 'USER/USER_ADD_ROLE_ERROR';

export const USER_DELETE_MODULE_START = 'USER/USER_DELETE_MODULE_START';
export const USER_DELETE_MODULE_SUCCESS = 'USER/USER_DELETE_MODULE_SUCCESS';
export const USER_DELETE_MODULE_ERROR = 'USER/USER_DELETE_MODULE_ERROR';

export const USER_DELETE_ROLE_START = 'USER/USER_DELETE_ROLE_START';
export const USER_DELETE_ROLE_SUCCESS = 'USER/USER_DELETE_ROLE_SUCCESS';
export const USER_DELETE_ROLE_ERROR = 'USER/USER_DELETE_ROLE_ERROR';

export const USER_MODULES_FETCH_DATA_START = 'USER/USER_MODULES_FETCH_DATA_START';
export const USER_MODULES_FETCH_DATA_SUCCESS = 'USER/USER_MODULES_FETCH_DATA_SUCCESS';
export const USER_MODULES_FETCH_DATA_ERROR = 'USER/USER_MODULES_FETCH_DATA_ERROR';

export const USER_ROLES_FETCH_DATA_START = 'USER/USER_ROLES_FETCH_DATA_START';
export const USER_ROLES_FETCH_DATA_SUCCESS = 'USER/USER_ROLES_FETCH_DATA_SUCCESS';
export const USER_ROLES_FETCH_DATA_ERROR = 'USER/USER_ROLES_FETCH_DATA_ERROR';

export const fetchUsersData = makeApiActionCreator(api.fetchUsersData, USERS_FETCH_DATA_START, USERS_FETCH_DATA_SUCCESS, USERS_FETCH_DATA_ERROR);
export const deleteUser = makeApiActionCreator(api.deleteUser, USER_REMOVE_START, USER_REMOVE_SUCCESS, USER_REMOVE_ERROR);
export const addUser = makeApiActionCreator(api.addUser, USER_ADD_START, USER_ADD_SUCCESS, USER_ADD_ERROR);
export const addUserModule = makeApiActionCreator(api.addUserModule, USER_ADD_MODULE_START, USER_ADD_MODULE_SUCCESS, USER_ADD_MODULE_ERROR);
export const fetchUserModules = makeApiActionCreator(api.fetchUserModules, USER_MODULES_FETCH_DATA_START, USER_MODULES_FETCH_DATA_SUCCESS, USER_MODULES_FETCH_DATA_ERROR);
export const deleteUserModule = makeApiActionCreator(api.deleteUserModule, USER_DELETE_MODULE_START, USER_DELETE_MODULE_SUCCESS, USER_DELETE_MODULE_ERROR);
export const addRoleUser = makeApiActionCreator(api.addRoleUser, USER_ADD_ROLE_START, USER_ADD_ROLE_SUCCESS, USER_ADD_ROLE_ERROR);
export const deleteUserRole = makeApiActionCreator(api.deleteUserRole, USER_DELETE_ROLE_START, USER_DELETE_ROLE_SUCCESS, USER_DELETE_ROLE_ERROR);
export const editUserName = makeApiActionCreator(api.editUserName, USER_EDIT_NAME_START, USER_EDIT_NAME_SUCCESS, USER_EDIT_NAME_ERROR);
export const fetchUserRoles = makeApiActionCreator(api.fetchUserRoles, USER_ROLES_FETCH_DATA_START, USER_ROLES_FETCH_DATA_SUCCESS, USER_ROLES_FETCH_DATA_ERROR);

export function editUser (user, roleData) {
  return {
    type: USER_EDIT_SUCCESS,
    user, roleData
  };
}
